# baseURL = 'https://blog.wox.cool/'
languageCode = 'zh-cn'
title = 'ceneax'
theme = 'hello-friend'
paginate = 10

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false